### ISSUE TITLE
Using with multiple EditBox'es

### ISSUE THREAD

**Issue by jbek7** [akshay2211/Numpad#1]
How do you use `Numpad` with multiple `EditBox`'es?

**Comment by akshay2211** [comment]
Dear @jama707 first of all, thank you for using this library.
can you explain a bit more what do you want to achieve, as you can use n number of `EditBox`'es and set their instance accordingly to set text

```
    numpad.setOnTextChangeListner((String text, int digits_remaining) -> {

                   Log.d("input",text+"  "+digits_remaining);

                   if(condition1) {
                   et1.settext(text);
                   } else {
                   et2.settext(text);
                   }
                }); 
```
