### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by sudheeshde** [akshay2211/Numpad#4]
When tapping on a number in the keypad there is a pink color appears in the background. How to remove/customize it ?

**Comment by akshay2211** [comment]
Hello @sudheeshde 
you can create your own drawable file and put it in Notepad widget

`numpad:numpad_background_resource="@drawable/numpad_background"`

just like [this](https://github.com/akshay2211/Numpad/blob/master/numpad/src/main/res/drawable/numpad_background.xml)

**Comment by sudheeshde** [comment]
Yup, that worked. Thanks @akshay2211
